//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHairdresser.Client.MessagesServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.MessagesServices.User receiverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.MessagesServices.User senderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string textField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageID {
            get {
                return this.MessageIDField;
            }
            set {
                if ((this.MessageIDField.Equals(value) != true)) {
                    this.MessageIDField = value;
                    this.RaisePropertyChanged("MessageID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.MessagesServices.User receiverID {
            get {
                return this.receiverIDField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverIDField, value) != true)) {
                    this.receiverIDField = value;
                    this.RaisePropertyChanged("receiverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.MessagesServices.User senderID {
            get {
                return this.senderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.senderIDField, value) != true)) {
                    this.senderIDField = value;
                    this.RaisePropertyChanged("senderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.MessagesServices.JobAppointment[] JobAppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.MessagesServices.JobAppointment[] JobAppointments {
            get {
                return this.JobAppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobAppointmentsField, value) != true)) {
                    this.JobAppointmentsField = value;
                    this.RaisePropertyChanged("JobAppointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFacebook {
            get {
                return this.UserFacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFacebookField, value) != true)) {
                    this.UserFacebookField = value;
                    this.RaisePropertyChanged("UserFacebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((this.UserGuidField.Equals(value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeClient {
            get {
                return this.typeClientField;
            }
            set {
                if ((object.ReferenceEquals(this.typeClientField, value) != true)) {
                    this.typeClientField = value;
                    this.RaisePropertyChanged("typeClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobAppointment", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class JobAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.MessagesServices.User HairdresserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HourJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobAppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJob {
            get {
                return this.DateJobField;
            }
            set {
                if ((this.DateJobField.Equals(value) != true)) {
                    this.DateJobField = value;
                    this.RaisePropertyChanged("DateJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.MessagesServices.User Hairdresser {
            get {
                return this.HairdresserField;
            }
            set {
                if ((object.ReferenceEquals(this.HairdresserField, value) != true)) {
                    this.HairdresserField = value;
                    this.RaisePropertyChanged("Hairdresser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HourJob {
            get {
                return this.HourJobField;
            }
            set {
                if ((this.HourJobField.Equals(value) != true)) {
                    this.HourJobField = value;
                    this.RaisePropertyChanged("HourJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobAppID {
            get {
                return this.JobAppIDField;
            }
            set {
                if ((this.JobAppIDField.Equals(value) != true)) {
                    this.JobAppIDField = value;
                    this.RaisePropertyChanged("JobAppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessagesServices.IMessagesService")]
    public interface IMessagesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/AddMessage", ReplyAction="http://tempuri.org/IMessagesService/AddMessageResponse")]
        bool AddMessage(GetHairdresser.Client.MessagesServices.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/AddMessage", ReplyAction="http://tempuri.org/IMessagesService/AddMessageResponse")]
        System.Threading.Tasks.Task<bool> AddMessageAsync(GetHairdresser.Client.MessagesServices.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/EditMessage", ReplyAction="http://tempuri.org/IMessagesService/EditMessageResponse")]
        bool EditMessage(GetHairdresser.Client.MessagesServices.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/EditMessage", ReplyAction="http://tempuri.org/IMessagesService/EditMessageResponse")]
        System.Threading.Tasks.Task<bool> EditMessageAsync(GetHairdresser.Client.MessagesServices.Message message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/DeleteMessage", ReplyAction="http://tempuri.org/IMessagesService/DeleteMessageResponse")]
        bool DeleteMessage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/DeleteMessage", ReplyAction="http://tempuri.org/IMessagesService/DeleteMessageResponse")]
        System.Threading.Tasks.Task<bool> DeleteMessageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/GetListMessagesForUser", ReplyAction="http://tempuri.org/IMessagesService/GetListMessagesForUserResponse")]
        GetHairdresser.Client.MessagesServices.Message[] GetListMessagesForUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessagesService/GetListMessagesForUser", ReplyAction="http://tempuri.org/IMessagesService/GetListMessagesForUserResponse")]
        System.Threading.Tasks.Task<GetHairdresser.Client.MessagesServices.Message[]> GetListMessagesForUserAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessagesServiceChannel : GetHairdresser.Client.MessagesServices.IMessagesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagesServiceClient : System.ServiceModel.ClientBase<GetHairdresser.Client.MessagesServices.IMessagesService>, GetHairdresser.Client.MessagesServices.IMessagesService {
        
        public MessagesServiceClient() {
        }
        
        public MessagesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddMessage(GetHairdresser.Client.MessagesServices.Message message) {
            return base.Channel.AddMessage(message);
        }
        
        public System.Threading.Tasks.Task<bool> AddMessageAsync(GetHairdresser.Client.MessagesServices.Message message) {
            return base.Channel.AddMessageAsync(message);
        }
        
        public bool EditMessage(GetHairdresser.Client.MessagesServices.Message message) {
            return base.Channel.EditMessage(message);
        }
        
        public System.Threading.Tasks.Task<bool> EditMessageAsync(GetHairdresser.Client.MessagesServices.Message message) {
            return base.Channel.EditMessageAsync(message);
        }
        
        public bool DeleteMessage(int id) {
            return base.Channel.DeleteMessage(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMessageAsync(int id) {
            return base.Channel.DeleteMessageAsync(id);
        }
        
        public GetHairdresser.Client.MessagesServices.Message[] GetListMessagesForUser(int id) {
            return base.Channel.GetListMessagesForUser(id);
        }
        
        public System.Threading.Tasks.Task<GetHairdresser.Client.MessagesServices.Message[]> GetListMessagesForUserAsync(int id) {
            return base.Channel.GetListMessagesForUserAsync(id);
        }
    }
}
