//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHairdresser.Client.HairdressInfoServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HairdresInfo", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common.Entities")]
    [System.SerializableAttribute()]
    public partial class HairdresInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.HairdressInfoServices.User HairdressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HairdressInfoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string map_dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string photoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ratingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.HairdressInfoServices.User HairdressID {
            get {
                return this.HairdressIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HairdressIDField, value) != true)) {
                    this.HairdressIDField = value;
                    this.RaisePropertyChanged("HairdressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HairdressInfoID {
            get {
                return this.HairdressInfoIDField;
            }
            set {
                if ((this.HairdressInfoIDField.Equals(value) != true)) {
                    this.HairdressInfoIDField = value;
                    this.RaisePropertyChanged("HairdressInfoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string map_data {
            get {
                return this.map_dataField;
            }
            set {
                if ((object.ReferenceEquals(this.map_dataField, value) != true)) {
                    this.map_dataField = value;
                    this.RaisePropertyChanged("map_data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string photo {
            get {
                return this.photoField;
            }
            set {
                if ((object.ReferenceEquals(this.photoField, value) != true)) {
                    this.photoField = value;
                    this.RaisePropertyChanged("photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.HairdressInfoServices.JobAppointment[] JobAppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.HairdressInfoServices.JobAppointment[] JobAppointments {
            get {
                return this.JobAppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobAppointmentsField, value) != true)) {
                    this.JobAppointmentsField = value;
                    this.RaisePropertyChanged("JobAppointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFacebook {
            get {
                return this.UserFacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFacebookField, value) != true)) {
                    this.UserFacebookField = value;
                    this.RaisePropertyChanged("UserFacebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((this.UserGuidField.Equals(value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeClient {
            get {
                return this.typeClientField;
            }
            set {
                if ((object.ReferenceEquals(this.typeClientField, value) != true)) {
                    this.typeClientField = value;
                    this.RaisePropertyChanged("typeClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobAppointment", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class JobAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.HairdressInfoServices.User HairdresserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HourJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobAppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJob {
            get {
                return this.DateJobField;
            }
            set {
                if ((this.DateJobField.Equals(value) != true)) {
                    this.DateJobField = value;
                    this.RaisePropertyChanged("DateJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.HairdressInfoServices.User Hairdresser {
            get {
                return this.HairdresserField;
            }
            set {
                if ((object.ReferenceEquals(this.HairdresserField, value) != true)) {
                    this.HairdresserField = value;
                    this.RaisePropertyChanged("Hairdresser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HourJob {
            get {
                return this.HourJobField;
            }
            set {
                if ((this.HourJobField.Equals(value) != true)) {
                    this.HourJobField = value;
                    this.RaisePropertyChanged("HourJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobAppID {
            get {
                return this.JobAppIDField;
            }
            set {
                if ((this.JobAppIDField.Equals(value) != true)) {
                    this.JobAppIDField = value;
                    this.RaisePropertyChanged("JobAppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HairdressInfoServices.IHairdressInfoService")]
    public interface IHairdressInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairdressInfoService/GetHairdressInform", ReplyAction="http://tempuri.org/IHairdressInfoService/GetHairdressInformResponse")]
        GetHairdresser.Client.HairdressInfoServices.HairdresInfo GetHairdressInform(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairdressInfoService/GetHairdressInform", ReplyAction="http://tempuri.org/IHairdressInfoService/GetHairdressInformResponse")]
        System.Threading.Tasks.Task<GetHairdresser.Client.HairdressInfoServices.HairdresInfo> GetHairdressInformAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairdressInfoService/SetHairdressInform", ReplyAction="http://tempuri.org/IHairdressInfoService/SetHairdressInformResponse")]
        bool SetHairdressInform(GetHairdresser.Client.HairdressInfoServices.HairdresInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHairdressInfoService/SetHairdressInform", ReplyAction="http://tempuri.org/IHairdressInfoService/SetHairdressInformResponse")]
        System.Threading.Tasks.Task<bool> SetHairdressInformAsync(GetHairdresser.Client.HairdressInfoServices.HairdresInfo info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHairdressInfoServiceChannel : GetHairdresser.Client.HairdressInfoServices.IHairdressInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HairdressInfoServiceClient : System.ServiceModel.ClientBase<GetHairdresser.Client.HairdressInfoServices.IHairdressInfoService>, GetHairdresser.Client.HairdressInfoServices.IHairdressInfoService {
        
        public HairdressInfoServiceClient() {
        }
        
        public HairdressInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HairdressInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HairdressInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HairdressInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GetHairdresser.Client.HairdressInfoServices.HairdresInfo GetHairdressInform(int id) {
            return base.Channel.GetHairdressInform(id);
        }
        
        public System.Threading.Tasks.Task<GetHairdresser.Client.HairdressInfoServices.HairdresInfo> GetHairdressInformAsync(int id) {
            return base.Channel.GetHairdressInformAsync(id);
        }
        
        public bool SetHairdressInform(GetHairdresser.Client.HairdressInfoServices.HairdresInfo info) {
            return base.Channel.SetHairdressInform(info);
        }
        
        public System.Threading.Tasks.Task<bool> SetHairdressInformAsync(GetHairdresser.Client.HairdressInfoServices.HairdresInfo info) {
            return base.Channel.SetHairdressInformAsync(info);
        }
    }
}
