//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHairdresser.Client.UserServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.UserServices.JobAppointment[] JobAppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFacebookField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeClientField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.UserServices.JobAppointment[] JobAppointments {
            get {
                return this.JobAppointmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobAppointmentsField, value) != true)) {
                    this.JobAppointmentsField = value;
                    this.RaisePropertyChanged("JobAppointments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFacebook {
            get {
                return this.UserFacebookField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFacebookField, value) != true)) {
                    this.UserFacebookField = value;
                    this.RaisePropertyChanged("UserFacebook");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid {
            get {
                return this.UserGuidField;
            }
            set {
                if ((this.UserGuidField.Equals(value) != true)) {
                    this.UserGuidField = value;
                    this.RaisePropertyChanged("UserGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gender {
            get {
                return this.genderField;
            }
            set {
                if ((object.ReferenceEquals(this.genderField, value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeClient {
            get {
                return this.typeClientField;
            }
            set {
                if ((object.ReferenceEquals(this.typeClientField, value) != true)) {
                    this.typeClientField = value;
                    this.RaisePropertyChanged("typeClient");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobAppointment", Namespace="http://schemas.datacontract.org/2004/07/GetHairDresser.Common")]
    [System.SerializableAttribute()]
    public partial class JobAppointment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GetHairdresser.Client.UserServices.User HairdresserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HourJobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JobAppIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateJob {
            get {
                return this.DateJobField;
            }
            set {
                if ((this.DateJobField.Equals(value) != true)) {
                    this.DateJobField = value;
                    this.RaisePropertyChanged("DateJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GetHairdresser.Client.UserServices.User Hairdresser {
            get {
                return this.HairdresserField;
            }
            set {
                if ((object.ReferenceEquals(this.HairdresserField, value) != true)) {
                    this.HairdresserField = value;
                    this.RaisePropertyChanged("Hairdresser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HourJob {
            get {
                return this.HourJobField;
            }
            set {
                if ((this.HourJobField.Equals(value) != true)) {
                    this.HourJobField = value;
                    this.RaisePropertyChanged("HourJob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int JobAppID {
            get {
                return this.JobAppIDField;
            }
            set {
                if ((this.JobAppIDField.Equals(value) != true)) {
                    this.JobAppIDField = value;
                    this.RaisePropertyChanged("JobAppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServices.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        bool Login(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Login", ReplyAction="http://tempuri.org/IUserService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Register", ReplyAction="http://tempuri.org/IUserService/RegisterResponse")]
        bool Register(GetHairdresser.Client.UserServices.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/Register", ReplyAction="http://tempuri.org/IUserService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(GetHairdresser.Client.UserServices.User u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserData", ReplyAction="http://tempuri.org/IUserService/GetUserDataResponse")]
        GetHairdresser.Client.UserServices.User GetUserData(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserData", ReplyAction="http://tempuri.org/IUserService/GetUserDataResponse")]
        System.Threading.Tasks.Task<GetHairdresser.Client.UserServices.User> GetUserDataAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserDataByFacebook", ReplyAction="http://tempuri.org/IUserService/GetUserDataByFacebookResponse")]
        GetHairdresser.Client.UserServices.User GetUserDataByFacebook(string facebookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserDataByFacebook", ReplyAction="http://tempuri.org/IUserService/GetUserDataByFacebookResponse")]
        System.Threading.Tasks.Task<GetHairdresser.Client.UserServices.User> GetUserDataByFacebookAsync(string facebookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditData", ReplyAction="http://tempuri.org/IUserService/EditDataResponse")]
        bool EditData(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/EditData", ReplyAction="http://tempuri.org/IUserService/EditDataResponse")]
        System.Threading.Tasks.Task<bool> EditDataAsync(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserType", ReplyAction="http://tempuri.org/IUserService/GetUserTypeResponse")]
        string GetUserType(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserType", ReplyAction="http://tempuri.org/IUserService/GetUserTypeResponse")]
        System.Threading.Tasks.Task<string> GetUserTypeAsync(GetHairdresser.Client.UserServices.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SetUserType", ReplyAction="http://tempuri.org/IUserService/SetUserTypeResponse")]
        bool SetUserType(GetHairdresser.Client.UserServices.User user, string userType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SetUserType", ReplyAction="http://tempuri.org/IUserService/SetUserTypeResponse")]
        System.Threading.Tasks.Task<bool> SetUserTypeAsync(GetHairdresser.Client.UserServices.User user, string userType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : GetHairdresser.Client.UserServices.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<GetHairdresser.Client.UserServices.IUserService>, GetHairdresser.Client.UserServices.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.Login(user);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.LoginAsync(user);
        }
        
        public bool Register(GetHairdresser.Client.UserServices.User u) {
            return base.Channel.Register(u);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(GetHairdresser.Client.UserServices.User u) {
            return base.Channel.RegisterAsync(u);
        }
        
        public GetHairdresser.Client.UserServices.User GetUserData(System.Guid id) {
            return base.Channel.GetUserData(id);
        }
        
        public System.Threading.Tasks.Task<GetHairdresser.Client.UserServices.User> GetUserDataAsync(System.Guid id) {
            return base.Channel.GetUserDataAsync(id);
        }
        
        public GetHairdresser.Client.UserServices.User GetUserDataByFacebook(string facebookId) {
            return base.Channel.GetUserDataByFacebook(facebookId);
        }
        
        public System.Threading.Tasks.Task<GetHairdresser.Client.UserServices.User> GetUserDataByFacebookAsync(string facebookId) {
            return base.Channel.GetUserDataByFacebookAsync(facebookId);
        }
        
        public bool EditData(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.EditData(user);
        }
        
        public System.Threading.Tasks.Task<bool> EditDataAsync(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.EditDataAsync(user);
        }
        
        public string GetUserType(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.GetUserType(user);
        }
        
        public System.Threading.Tasks.Task<string> GetUserTypeAsync(GetHairdresser.Client.UserServices.User user) {
            return base.Channel.GetUserTypeAsync(user);
        }
        
        public bool SetUserType(GetHairdresser.Client.UserServices.User user, string userType) {
            return base.Channel.SetUserType(user, userType);
        }
        
        public System.Threading.Tasks.Task<bool> SetUserTypeAsync(GetHairdresser.Client.UserServices.User user, string userType) {
            return base.Channel.SetUserTypeAsync(user, userType);
        }
    }
}
