//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHairdresser.Client.JobAppointmentsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobAppointmentsService.IJobAppointmentsService")]
    public interface IJobAppointmentsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/AddJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/AddJobAppointmentResponse")]
        bool AddJobAppointment(GetHairDresser.Common.JobAppointment jobapp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/AddJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/AddJobAppointmentResponse")]
        System.Threading.Tasks.Task<bool> AddJobAppointmentAsync(GetHairDresser.Common.JobAppointment jobapp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/EditJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/EditJobAppointmentResponse")]
        bool EditJobAppointment(GetHairDresser.Common.JobAppointment jobapp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/EditJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/EditJobAppointmentResponse")]
        System.Threading.Tasks.Task<bool> EditJobAppointmentAsync(GetHairDresser.Common.JobAppointment jobapp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/DeleteJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/DeleteJobAppointmentResponse")]
        bool DeleteJobAppointment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/DeleteJobAppointment", ReplyAction="http://tempuri.org/IJobAppointmentsService/DeleteJobAppointmentResponse")]
        System.Threading.Tasks.Task<bool> DeleteJobAppointmentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsByDate", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsByDateResponse")]
        GetHairDresser.Common.JobAppointment[] GetJobAppointmentsByDate(GetHairDresser.Common.User user, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsByDate", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsByDateResponse")]
        System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetJobAppointmentsByDateAsync(GetHairDresser.Common.User user, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetJobAppointments", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsResponse")]
        GetHairDresser.Common.JobAppointment[] GetJobAppointments(GetHairDresser.Common.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetJobAppointments", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetJobAppointmentsResponse")]
        System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetJobAppointmentsAsync(GetHairDresser.Common.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetTypedJobAppointmentsByDate", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetTypedJobAppointmentsByDateResponse")]
        GetHairDresser.Common.JobAppointment[] GetTypedJobAppointmentsByDate(GetHairDresser.Common.User user, int status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobAppointmentsService/GetTypedJobAppointmentsByDate", ReplyAction="http://tempuri.org/IJobAppointmentsService/GetTypedJobAppointmentsByDateResponse")]
        System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetTypedJobAppointmentsByDateAsync(GetHairDresser.Common.User user, int status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobAppointmentsServiceChannel : GetHairdresser.Client.JobAppointmentsService.IJobAppointmentsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobAppointmentsServiceClient : System.ServiceModel.ClientBase<GetHairdresser.Client.JobAppointmentsService.IJobAppointmentsService>, GetHairdresser.Client.JobAppointmentsService.IJobAppointmentsService {
        
        public JobAppointmentsServiceClient() {
        }
        
        public JobAppointmentsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobAppointmentsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobAppointmentsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobAppointmentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddJobAppointment(GetHairDresser.Common.JobAppointment jobapp) {
            return base.Channel.AddJobAppointment(jobapp);
        }
        
        public System.Threading.Tasks.Task<bool> AddJobAppointmentAsync(GetHairDresser.Common.JobAppointment jobapp) {
            return base.Channel.AddJobAppointmentAsync(jobapp);
        }
        
        public bool EditJobAppointment(GetHairDresser.Common.JobAppointment jobapp) {
            return base.Channel.EditJobAppointment(jobapp);
        }
        
        public System.Threading.Tasks.Task<bool> EditJobAppointmentAsync(GetHairDresser.Common.JobAppointment jobapp) {
            return base.Channel.EditJobAppointmentAsync(jobapp);
        }
        
        public bool DeleteJobAppointment(int id) {
            return base.Channel.DeleteJobAppointment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteJobAppointmentAsync(int id) {
            return base.Channel.DeleteJobAppointmentAsync(id);
        }
        
        public GetHairDresser.Common.JobAppointment[] GetJobAppointmentsByDate(GetHairDresser.Common.User user, System.DateTime date) {
            return base.Channel.GetJobAppointmentsByDate(user, date);
        }
        
        public System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetJobAppointmentsByDateAsync(GetHairDresser.Common.User user, System.DateTime date) {
            return base.Channel.GetJobAppointmentsByDateAsync(user, date);
        }
        
        public GetHairDresser.Common.JobAppointment[] GetJobAppointments(GetHairDresser.Common.User user) {
            return base.Channel.GetJobAppointments(user);
        }
        
        public System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetJobAppointmentsAsync(GetHairDresser.Common.User user) {
            return base.Channel.GetJobAppointmentsAsync(user);
        }
        
        public GetHairDresser.Common.JobAppointment[] GetTypedJobAppointmentsByDate(GetHairDresser.Common.User user, int status) {
            return base.Channel.GetTypedJobAppointmentsByDate(user, status);
        }
        
        public System.Threading.Tasks.Task<GetHairDresser.Common.JobAppointment[]> GetTypedJobAppointmentsByDateAsync(GetHairDresser.Common.User user, int status) {
            return base.Channel.GetTypedJobAppointmentsByDateAsync(user, status);
        }
    }
}
